env:
  es6: true
  node: true
  mocha: true
  jquery: false
  browser: false
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
plugins:
  - mocha
rules:
  quotes: off
  indent: off
  no-unused-vars: off
  prefer-const: warn
  no-var: warn
  complexity:
    - warn
    - max: 5
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-cond-assign:
    - warn
    - except-parens
  no-console: warn
  no-useless-escape: off
  "mocha/no-exclusive-tests": "warn"
